.TH llist_empty 3 "June 2018" "Holberton School"

.SH NAME
llist_is_empty - Checks if a list is empty

.SH SYNOPSIS
.B #include <llist.h>

.BI "int llist_is_empty(llist_t *" "list" ");"

.SH DESCRIPTION
.BR "llist_empty" "() will check whether if the linked list pointed to by"
.IR "list" " is empty."

.SH RETURN VALUE
.BR "llist_empty" "() returns 0 if"
.IR "list" " contains at least one node. 1 is returned otherwise, or if an error occured."

.SH SEE ALSO
.BR "llist_add_node" "(3),"
.BR "llist_append" "(3),"
.BR "llist_create" "(3),"
.BR "llist_destroy" "(3),"
.BR "llist_find_node" "(3),"
.BR "llist_for_each" "(3),"
.BR "llist_get_head" "(3),"
.BR "llist_get_node_at" "(3),"
.BR "llist_get_tail" "(3),"
.BR "llist_insert_node" "(3),"
.BR "llist_pop" "(3),"
.BR "llist_remove_node" "(3),"
.BR "llist_reverse" "(3),"
.BR "llist_size" "(3),"
.BR "llist_sort" "(3)"
