.TH llist_for_each 3 "June 2018" "Holberton School"

.SH NAME
llist_for_each - Operates on each element of a list

.SH SYNOPSIS
.B #include <llist.h>

.BI "typedef void *" "llist_node_t" ";"

.BI "typedef int (*" "node_func_t" ")(llist_node_t, unsigned int, void *);"

.BI "int llist_for_each(llist_t *" "list" ", node_func_t " "action" ", void *" "arg" ");"

.SH DESCRIPTION
.BR "llist_for_each" "() loops through each node of the linked list pointed to by"
.IR "list" ", and call the function pointed to by " "action" ", with a pointer to the node, its index, and " "arg" "."

.BR "llist_for_each" "() interrupts its loop as soon as"
.IR "action" " returns a non-zero value."

.SH RETURN VALUE
.RB "Upon success, " "llist_for_each" "() returns 0."

.RI "If " "action" " returned a non-zero value, the for_each loop is interrupted, and the last value returned by " "action" " is returned."

.R "In case of error, -1 is returned, and the global variable"
.IR "llist_errno" " is set with the appropriate value."

.SH ERRORS
.B LLIST_NULL_ARGUMENT
.RS
.RI "Either " "list" " or " "action" " points to NULL."
.RE

.B LLIST_MULTITHREAD_ISSUE
.RS
.RI "Only if " "flags" " was set to"
.BR "MT_SUPPORT_TRUE" " when"
.IR "list" " was created. An error occured whith multithreading safety."
.RE

.SH SEE ALSO
.BR "llist_add_node" "(3),"
.BR "llist_append" "(3),"
.BR "llist_create" "(3),"
.BR "llist_destroy" "(3),"
.BR "llist_empty" "(3),"
.BR "llist_find_node" "(3),"
.BR "llist_get_head" "(3),"
.BR "llist_get_node_at" "(3),"
.BR "llist_get_tail" "(3),"
.BR "llist_insert_node" "(3),"
.BR "llist_pop" "(3),"
.BR "llist_remove_node" "(3),"
.BR "llist_reverse" "(3),"
.BR "llist_size" "(3),"
.BR "llist_sort" "(3)"
